package model

const INVALID_BODY = "Datos invalidos"
const CONNECTION_DB_SUCCESSFULL = "Conexion realizada con exito"
const URL_BD = "mongodb://localhost:27017/"
const DB_NAME = "tasker"
const COLLECTION = "task"
const CONNECTION_DB_ERROR = "No se puede conectar con la base de datos"
const CONNECTION_DB_ERROR_PING = "Imposible alcanzar el host"
const SAVE_NEW_DATA_ERROR = "A ocurrido un error guardando en Base de datos"
const SAVE_NEW_DATA_SUCCESS = "Tarea creada exitosamente"
const GET_ALL_ERROR = "Error consultando todas las tareas"
const GET_ALL_SUCCESS = "Listado de Tareas"
const COMPLETED_DATA_ERROR = "A ocurrido un error actualizando el estado"
const COMPLETED_DATA_SUCCESS = "Estado cambiado con exito"
const INVALID_ID = "El id es invalido"
const INVALID_ID_NOT_EXIST = "El id no se encuentra registrado"
const DELETE_ERROR = "A ocurrido un error eliminando el registro"
const DELETE_SUCCESS = "Registro eliminado con exito"
